zstyle :compinstall filename '${ZDOTDIR:-$HOME}.zshrc'

# zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "${ZINIT_HOME}/zinit.zsh"

# Options
setopt autocd

# Save command history
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=2000
SAVEHIST=1000

# History Options
setopt hist_find_no_dups	# Don't show duplicate entries while searching history
setopt append_history		# Allow multiple sessions to append to one history
setopt inc_append_history	# Write commands to history on-the-fly. Don't wait shell to exits 
setopt share_history		# Share history among sessions

# vi bindings
bindkey -v

# zinit plugins
# Plugins
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting
zinit light 'zsh-users/zsh-history-substring-search'

# zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# zsh-completions
# While using Homebrew, tools like uv or cargo install completions in the fpath.
# If these tools are installed manually, we must add these completions on our own.
fpath=(${XDG_DATA_HOME}:-${HOME}/.local/share/zsh/zfunc $fpath)

# Completion
# https://stackoverflow.com/a/30840986
autoload -Uz compinit
compinit

setopt complete_in_word # /u/loc/b<TAB> to /usr/local/bin
setopt glob_dots

zstyle ':completion:*' menu select 

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format "$fg[yellow]%B--- %d%b"
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format "$fg[red]No matches for:$reset_color %d"
zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'
zstyle ':completion:*' group-name ''
